/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.serivesmejia.DZipper.Frame;

import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;

import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import net.lingala.zip4j.core.ZipFile;
import net.lingala.zip4j.exception.ZipException;

/**
 *
 * @author Sebastian
 */
public class OLD_MainFrame extends java.awt.Frame {

    JFileChooser chooser;
     Boolean file = false;
    
    public OLD_MainFrame(String title, Logger logger) {
        initComponents();
        setTitle(title);
        setSize(770, 560);
        setLocationRelativeTo(null);
        MenuItem mi = new MenuItem();
        mi.setLabel("Open zip file...");        
        
        mi.addActionListener(new java.awt.event.ActionListener(){  
            @Override
            public void actionPerformed(ActionEvent ae) {
               searchZip(); 
            }
        
            
            
        });
        menu1.add(mi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();

        setName(""); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        textArea1.setEditable(false);
        add(textArea1, java.awt.BorderLayout.CENTER);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setMenuBar(menuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

private void searchZip(){
        chooser = new JFileChooser();
                   
               
        chooser.setDialogTitle("Select a zip file");
        chooser.setCurrentDirectory(new java.io.File("Desktop"));
        chooser.setAcceptAllFileFilterUsed(false);
               
        File file1;
        
     if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
         
      System.out.println("getCurrentDirectory(): " +  chooser.getCurrentDirectory());
      System.out.println("getSelectedFile() : " +  chooser.getSelectedFile());
      file = true;
      file1 = chooser.getSelectedFile();
      
      if(file1 == null){
          System.out.println("No Selection");
      }else{
          String appdata = System.getenv("APPDATA");
       try {
       ZipFile zipFile = new ZipFile(file1);
         zipFile.extractAll(appdata+"\\DZipper\\tmp\\" + file1.getName() + "\\");
         setTitle("DZipper - " + file1.getName());
         textArea1.setText("");
    } catch (ZipException e) {
        e.printStackTrace();
        setTitle("DZipper - No file opened");
        DialogForm.main("The file isn't in a valid form or it's corrupted", "Error");
        return;
    }
       
       //for(File fl : new new File(appdata+"\\DZipper\\tmp\\" + file1.getName() + "\\")){
          
      //}
       
      for (final File fileEntry : new File(appdata+"\\DZipper\\tmp\\" + file1.getName() + "\\").listFiles()) {
          if(fileEntry.isDirectory()){
              textArea1.setText(textArea1.getText() + "[FOLDER] : " + fileEntry.getName() +"\n");
           System.out.println(fileEntry.getName());
          }
      }
      
       for(File fl : new File(appdata+"\\DZipper\\tmp\\" + file1.getName() + "\\").listFiles()){
                  if(!fl.isDirectory()){
                  textArea1.setText(textArea1.getText() + "[FILE] : " + fl.getName() +"\n");
           System.out.println(fl.getName());
                  }
       }
       
       
      }
      
      }else{
      System.out.println("No Selection ");
      }
}

}
